config/routes.rb
Breeze::Application.routes.draw do
  resources :users, :posts, :comments

  resources :posts do
    resource :comments
  end
  namespace :admin do
    resources :posts
  end

  root :to  => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :author_name, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  has_many :comments

  validates_presence_of :title, :body, :author
  validates_length_of :title, :minimum => 3

  default_scope :order => "created_at DESC"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, :as => :author
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  respond_to :html

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to root_path
    else
      render :edit
    end
  end

  def create
    @post = Post.new(params[:post])
    if @post.save
       redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # TODO do authentication for this controller.

  def create
    @comment = Comment.new(params[:comment])
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to @comment.post, :flash => { success: "Comment created." }
    else
      redirect_to @comment.post, error: "Couldn't create comment.'"
    end
  end

  def destroy
    # TODO check for current_user
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to @comment.post, :flash => { error: "Comment deleted." }
    else
      redirect_to @comment.post, error: "Comment was not deleted."
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def show_delete_link(comment)
    # TODO implement proper user login and change this here.
    link_to("Delete", comment_path(comment), :method => :delete)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/edit.html.erb
<%= semantic_form_for(@post, :url => admin_post_path(@post)) do |f| %>
    <%= f.inputs %>
    <%= f.buttons %>
<% end %>

app/views/admin/posts/new.html.erb
<%= semantic_form_for(@post, :url => admin_posts_path) do |f| %>
    <%= f.inputs %>
    <%= f.buttons %>
<% end %>

app/views/comments/_comment.html.erb
<article class="comment">
  <%= comment.author_name %>:
  <%= comment.body %>
  <%= show_delete_link(comment) %>
</article>

app/views/comments/_form.html.erb
<%=  semantic_form_for(@comment, :url => post_comments_path(params[:id])) do |f| %>
    <%= f.inputs do %>
        <%= f.input :author_name %>
        <%= f.input :body %>
    <% end %>
    <%= f.buttons %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breeze</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="cloud-1"></div>
    <div id="cloud-2"></div>
    <div id="cloud-3"></div>
    <div id="cloud-4"></div>
    <div id="cloud-5"></div>
    <div id="wrap">
      <!-- BEGIN HEADER -->
      <header>
        <nav>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><a href="blub">About</a></li>
            <li><a href="blub">Media</a></li>
            <li><a href="blub">Contact us</a></li>
            <li><a href="blub">AWESOME</a></li>
          </ul>
        </nav>
      </header>
      <!-- END HEADER -->
      <!-- BEGIN HIGHLIGHTS -->
      <section id="highlights">
        <%= image_tag('header_gallery.png', :width => '960px', :height => '390px') %>
        <div id="highlights-title">New artwork for the shizzle!</div>
        <div id="highlights-navigation">1 2 3 </div>
      </section>
      <!-- END HIGHLIGHTS -->
      <!-- BEGIN MAIN CONTENT -->
      <section id="main">
        <% flash.each do |name, msg| %>
          <div class="<%= name %>"><%= msg %></div>
        <% end %>

        <%= yield %>
      </section>
      <!-- END MAIN CONTENT -->
      <!-- BEGIN RIGHT BAR -->
      <section id="right-bar">
        right bar
      </section>
      <!-- END RIGHT BAR -->
    </div>
</body>
</html>

app/views/posts/_post.html.erb
<article class="post">
  <header>
    <h1><%= post.title %></h1>
  </header>
  <%= post.body %> by <%= link_to post.author.name, post.author %>
  <%= link_to "Show more", post %>

</article>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/show.html.erb
<article id="post">
  <header>
    <h1><%= @post.title %></h1>

    <h2><%= link_to @post.author.name, @post.author %></h2>
  </header>
  <%= @post.body %>
</article>
<section>
  <header>
    <h1>Comments:</h1>
  </header>
  <%= render @post.comments %>
  <%= render "comments/form" %>
</section>